name: Deploy to Linux Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy and start the project
      env:
        API_PORT: ${{ secrets.API_PORT }}
        SSH_IP: ${{ secrets.SSH_IP }}
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -p $SSH_PORT castberry@$SSH_IP << 'EOF'
          cd /home/castberry/be-rallyserve
          git pull origin main
          npm install
          # Find the process running on the API port and kill it
          pm2 restart rallyserve
        EOF
