name: Deploy to Linux Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy and start the project
      env:
        API_PORT: ${{ secrets.API_PORT }}
        SSH_IP: ${{ secrets.SSH_IP }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no -p $SSH_PORT castberry@$SSH_IP << 'EOF'
          cd /path/to/your/project
          git pull origin main
          npm install
          # Find the process running on the API port and kill it
          PID=$(lsof -ti tcp:$API_PORT)
          if [ ! -z "$PID" ]; then
            kill -9 $PID
          fi
          nohup npm run start &
          disown $!
        EOF